Fixes format of entry value if needed
BoldGrid/weforms pull request #141
Opened 2021-11-23 19:27 UTC by avonville

Updated fix for[ issue-61](https://github.com/BoldGrid/weforms-pro/issues/61) in pro.

2021-12-07 19:24 UTC, bwmarkle commented on includes/class-notification.php
> +     * used to find the value from the field settings.
Can we include a specific example?

```php
* For example, let's say we have the following options:
* DEPARTMENT / EMAIL
* Support / support@example.com
* Sales / sales@example.com
* 
* Users need the ability to pass {field:department} and get "Support",
* and {value:department} to get support@email.com
```

2021-12-09 15:30 UTC, jamesros161 requested changes

2021-12-09 15:30 UTC, jamesros161 commented on includes/class-form-entry-manager.php
> +     * @static
Just a comment, you should usually put the @static tag last. It's not a requirement, but it is customary. From what I've seen anyways.

2021-12-09 15:30 UTC, jamesros161 commented on includes/class-form-entry-manager.php
> +     * @param  array $field
Your @param is missing the description. Format is 

@param [type] [variable_name] [description].

2021-12-09 15:30 UTC, jamesros161 commented on includes/class-form-entry-manager.php
> +                $value = array_search( $field['value'], $field['options'] );
'=' not alligned

2021-12-09 15:30 UTC, jamesros161 commented on includes/class-form-entry.php
> +    public static function get_form_id( $entry_id ) {
MIssing function docblock. When you do add the docblock, be sure to add the @global tag. 
see https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#1-functions-class-methods

2021-12-09 15:30 UTC, jamesros161 commented on includes/class-notification.php
> +     * @param int    $entry_id
missing descriptions in doc block @param , and @return description

2021-12-10 15:58 UTC, jamesros161 approved these changes

2021-12-10 16:29 UTC, merged