Google Maps in Email will show Address. Fixes #45
BoldGrid/weforms pull request #86
Opened 2021-05-11 23:36 UTC by avonville

Email notification sends the array of data for Google Maps integration. Fixed to send the address from the google maps data. Currently, there is no way to add the map to an email. 

We could use the Map Static API in future enhancements, but this will need more testing and research.

Or we can have the google maps section of the email have a link to the entry within weforms.

2021-05-19 11:22 UTC, bwmarkle requested changes

2021-05-19 11:22 UTC, bwmarkle commented on includes/class-notification.php
> +            }elseif (in_array( $value['type'], [ 'google_map' ] ) ) {
Spacing. Change:
`}elseif (in_array( $value['type'], [ 'google_map' ] ) ) {`
to:
`} elseif ( in_array( $value['type'], ['google_map'] ) ) {`

Please see [space usage](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage).

----

[Use long array syntax](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#declaring-arrays). Change `[ 'google_map' ]` to `array( 'google_map' )`

2021-05-19 11:22 UTC, bwmarkle commented on includes/class-notification.php
> +            }elseif (in_array( $value['type'], [ 'google_map' ] ) ) {
![image](https://user-images.githubusercontent.com/5925563/118804651-f5874e80-b872-11eb-8ddc-479fba826296.png)

2021-05-19 18:09 UTC, avonville commented
@bwmarkle added the requested changes

2021-05-20 17:50 UTC, bwmarkle commented
Hi @avonville please review my comments on this one again. I don't believe they were all addressed.

2021-05-21 14:47 UTC, avonville commented
@bwmarkle fixed spacing issues.

2021-08-24 13:33 UTC, bwmarkle approved these changes

2021-08-24 19:34 UTC, merged